#pragma once

unordered_map<ModuleID, pair<string, string>> module_descriptions
{
	{ AntiCapture, {"Excludes this client window from capture. (Require >= Win10)", "从截屏或录屏中排除此客户端的窗口（至少需要 Win10）"}},
	{ AntiClose, {"If enabled, close messages are invalid for this client window.", "屏蔽所有对本客户端窗口的关闭消息。"}},
	{ AntiDebug, {"Prevent this client from being debugged.", "防止客户端被调试。"}},
	{ AntiInject, {"Prevents from any module injection of this client.", "防止客户端进程被注入。"}},
	{ AntiIntercept, {"Prevents from any interception of antivirus softwares.", "自动对一些杀软的拦截窗口按允许。"}},
	{ AntiMalware, {"Detects and confronts bad behaviours of malware.", "检测并对抗恶意软件的恶意行为。"}},
	{ AntiSpy, {"Prevent any spyware behaviours", "防止任何间谍软件的行为。" }},
	{ AntiMicrophone, {"Automatically mute capture devices to prevent recording.", "自动将采集设备静音，防止录音。"}},
	{ AntiTaskkill, {"Prevents from any taskkill command to this client.", "阻止所有对客户端有威胁的taskkill命令。"}},
	{ AntiMouseHook, {"Prevents from any normal mouse hooking.", "阻止普通的鼠标钩子。"}},
	{ AntiKeyHook, {"Prevents from any normal keyboard hooking.", "阻止普通的键盘钩子。"}},
	{ AutoStart, {"Automatically start this client when the system starts.", "系统启动时自动启动本客户端。"}},
	{ AutoUAC, {"Automatically press the yes button of the UAC prompt. ", "在UAC界面自动按“是”。"}},
	//{ AutoLogin, {"Automatically input user's password in the login UI.", "在登录界面自动输入用户密码。"}},
	{ Admin, {"Granted with Admin privileges.", "重启客户端获得管理员权限。"}},
	{ System, {"Granted with System privileges.", "重启客户端窃取系统权限。"}},
	{ UIAccess, {"Granted with UIAccess token privilege. (System Required)", "重启客户端窃取UIAccess特权。（需要系统权限）"}},
	{ SuperTopmost, {"Dynamically set super topmost for client windows. (PRO)", "动态设置客户端窗口为超级置顶。（专业版）"}},
	{ UACBypass, {"Bypasses the UAC prompt to obtain Admin privileges.", "绕过UAC弹窗获得管理员权限。"}},
	{ Taskmgr, {"Start the Task Manager.", "打开任务管理器。"}},
	{ Cmd, {"Start the Command Prompt.", "打开命令提示符。"}},
	{ SuperCmd, {"Start the Command Prompt with higher privileges.", "打开更高权限的命令提示符。"}},
	{ PowerShell, {"Start the PowerShell.", "打开 PowerShell。"}},
	{ Gpedit, {"Start the Group Policy Editor.", "打开组策略编辑器。"}},
	{ Perfmon, {"Start the Performance Monitor.", "打开资源监视器。"}},
	{ Regedit, {"Start the Registry Editor.", "打开注册表编辑器。"}},
	{ Osk, {"Start the On-Screen Keyboard.", "打开屏幕键盘。"}},
	{ Mrt, {"Start the Malicious Software Removal Tool.", "打开恶意程序删除工具。"}},
	{ CrackPassword, {"Brute Force the computer password of current user with a dictionary.", "凭借字典，暴力破解计算机当前用户的密码。"}},
	{ SetPassword, {"Clear or Set the login password of the user. (Admin Required)", "清除或设置计算机密码。（需要管理员）"}},
	{ ClearPin, {"Clear Windows PIN. (Reboot to Apply)", "清除 Windows PIN，重启生效。"}},
	{ Uninstaller, {"Automatically help you uninstall some softwares.", "自动帮你卸载一些软件。"}},
	{ Interceptor, {"Globally intercept some important functions in the system. (WIP)", "全局拦截系统的某些重要函数。 (维护中)"}},
	{ Gatekeeper, {"Intercept Winlogon Events by injecting a special DLL. (Admin + Privileges Required)", "通过注入动态链接库，拦截 Winlogon 事件（需要管理员和特权）"}},
	{ NoFirewall, {"Disable the Windows Firewall (No Admin Required).", "禁用系统防火墙（不需要管理员）"}},
	{ FreezeWinlogon, {"Suspend the winlogon.exe. Only works in lower versions of Windows.", "挂起 Winlogon。 只在低版本系统有效。"}},
	{ MagnifyReplace, {"Substitude the system Magnifier with the client. Press Win + = to start. (Admin Required)", "用本客户端的启动器替换系统放大镜。按下 Win + = 快捷启动。（需要管理员）"}},
	{ SethcBackdoor, {"Set the client as the Sethc Backdoor. Press Shift five times to start. (Admin Required)", "用本客户端的启动器替换系统粘滞键。按下五下 LShift 快捷启动。（需要管理员）"}},
	{ CrashKey, {"Turn on BSOD Shortcut (RCtrl + ScrollLock twice).", "开启蓝屏快捷键（按两次 右Ctrl + ScrollLock）。"}},
	{ Privileges, {"Obtain all available privileges.", "获得各项可用的特权。"}},
	{ Protection, {"Prevent the client from being terminated by User functions. (Sirius Driver Needed)", "为客户端启用进程保护，可以阻止一切用户层的终止进程函数。（需要 Sirius 驱动）"}},
	{ MachineLock, {"Lock this computer. (Be careful)", "锁定这台计算机（谨慎使用）。"}},
	{ LockUser, {"Lock current user immediately.", "立即锁定当前用户。"}},
	{ Logoff, {"Logoff the current user immediately.", "立即注销。"}},
	{ Shutdown, {"Shutdown the system immediately.", "立即关机。"}},
	{ Reboot, {"Reboot the system immediately.", "立即重启。"}},
	{ MythwareKiller, {"Destroy all the restrictions of Mythware and Uninstall it." , "摧毁一切极域的限制然后卸载它。"}},
	{ Crash, {"Trigger BSOD to crash Windows (No Admin Required)." , "触发蓝屏使系统崩溃。（不需要管理员）"}},

	{ ListTrays, {"List all the info of trays inside the taskbar.", "枚举任务栏中的托盘信息。" }},
	{ WindowManager, {"Manage windows with a visual manager app.", "使用可视化管理器管理窗口。" }},
	{ WindowTags, {"Show window info tags in the left-top corner of the windows.", "在窗口的左上角显示一个信息标签。" }},
	{ WindowHighlight, {"Highlight the window cursor points to with a rainbow rectangle.", "用彩虹色方框高亮当前窗口。" }},
	{ WindowESP, {"Display rectangles of the windows.", "绘制一切窗口的方框。" }},
	{ WindowKill, {"Kill the specified window.", "杀掉指定窗口。" }},
	{ WindowFreeze, {"Freeze the specified window.", "冻结指定窗口。" }},
	{ Tracers, {"Draw tracers from mouse cursor to the windows.", "绘制鼠标到窗口的追踪线。"}},
	{ OpacityChanger, {"Change the opacity of the target window.", "改变目标窗口不透明度。"}},
	{ ConsoleESP, {"Monitor the content of consoles of any applications.", "监控任意应用程序的控制台内容。"}},
	{ Messenger, {"Notify you when receive specific window messages.", "接收到指定窗口消息时通知。"}},
	{ MsgBlocker, {"Block the windows messages temporarily.", "临时阻塞窗口消息。" }},
	{ WindowMaster, {"Display a simple window panel, you can control foreground window using hotkeys.", "显示一个简易的窗口面板，你可以通过快捷键控制前端窗口。" }},
	{ PrivateWindow, {"Protect some of your private windows from screenrecording or screenshot.", "防止一些私人窗口被截屏或者录屏。"}},
	{ BandSetter, {"Dynamically set the z-order band of the specified windows. (PRO)", "动态设置指定窗口的Z序段。（专业版）"}},
	{ Topmost, {"Make the foreground window Topmost immediately. You need to assign a hotkey.", "立即置顶前端窗口。你需要分配一个快捷键。"}},
	{ TitleChanger, {"Modify the caption text of the foregrond window automatically.", "自动修改前端窗口的标题。"}},
	{ AutoTranslate, {"Automatically translate and display the texts of the target window.", "自动翻译并展示目标窗口的文本。"}},
	{ AutoFocus, {"Automatically focus on some windows.", "自动聚焦到某些窗口。"}},
	{ BetterAnimation, {"Customize the animation effects of the windows.", "自定义窗口动画效果。"}},
	{ ToastESP, {"Monitor Windows toast notifications and relay their title/body to the configured notification channel.", "监视 Windows 系统 Toast 通知并将标题/正文转发到指定通知渠道。"}},
	{ KeywordESP, {"Periodically run OCR on the screen/window and draw highlight boxes around any text matching the keyword list. Pro only.", "定期对屏幕或窗口执行 OCR，在匹配关键词的文字周围绘制高亮框。专业版独有。"}},
	{ AntiBrowser, {"Automatically close browsers or URL-links.", "自动关闭浏览器或者链接跳转。"}},
	{ AntiPopups, {"Automatically close some annoying windows.", "自动关闭一些恼人的弹窗。" }},
	{ AntiTopmost, {"Defend against OTHER Topmost windows.", "抵御其他置顶窗口。"}},
	{ CloseEnhance, {"Force Kill its process if a window hasn't closed after Alt+F4 is pressed.", "如果窗口在按下Alt+F4后没有关闭，就杀它的进程。" }},
	{ DialogEscape, {"Close it when any dialog box appear.", "关闭出现的标准对话框。" }},
	{ DialogPhysics, {"Apply physics effects to the dialog boxes.", "给对话框添加物理效果。"}},
	{ HideTaskbar, {"Hide the system taskbar.", "隐藏系统任务栏。" }},
	{ TargetHUD, {"Display a HUD for the target window.", "显示目标窗口的 HUD。" }},
	{ TargetESP, {"Mark the position of window target.", "标记目标窗口的位置。"}},
	{ UncrossAura, {"Disable the close button of every normal-styled window.", "禁用每一个目标窗口的标准风格关闭按钮。" }},
	{ FreezeAura, {"Freeze every target window.", "冻结每一个目标窗口。" }},
	{ AimAssist, {"Automatically aim at the target window with the mouse.", "自动瞄准目标窗口的右上角。" }},
	{ TriggerBot, {"Automatically click when the cursor is on the close button of a window.", "如果鼠标放在窗口右上角则自动点击。" }},
	{ KillAuraLegit, {"Close every target window after moving the cursor on its close button.", "自动移动鼠标到目标窗口右上角然后关闭它。" }},
	{ KillAura, {"Close every target window.", "自动关闭每一个目标窗口。" }},
	{ MaxAura, {"Maximize every target window.", "最大化每一个目标窗口。" }},
	{ MinAura, {"Minimize every target window.", "最小化每一个目标窗口。" }},
	{ Ruler, {"Draw a window ruler on the screen.", "在屏幕上绘制一个窗口标尺。" }},

	{ AntiProcCreate, {"Prevents new processes from being created using Sirius driver.", "使用 Sirius 驱动阻止新进程的创建。"}},
	{ Elevator, {"Elevate a process without restarting it using a driver.", "使用驱动程序提升进程权限，无需重启它。"}},
	{ ForceTerminator, {"Helps you terminate target processes forcibly using Sirius driver.", "使用 Sirius 驱动帮你强制终止目标进程。"}},
	{ ListModules, {"List all the modules of the specified process in Console." , "在控制台列举所有指定进程的模块。"}},
	{ ListDrivers, {"List all the kernel drivers of the system in Console." , "在控制台列举系统的所有内核驱动。"}},
	{ ListServices, {"List all the services of the system in Console." , "在控制台枚举系统的所有服务。"}},
	{ ListTasks, {"List all the scheduled tasks of the system in Console." , "在控制台列举系统的所有计划任务。"}},
	{ Injector, {"Inject/Uninject DLL into/from the specified process." , "向/从目标进程（取消）注入动态链接库。"}},
	{ RemoteRun, {"Run your command on another process by injecting code." , "通过注入代码，让另一个进程运行你的命令。"}},
	{ Speedhack, {"Speed up or slow down processes by injecting DLL." , "通过注入动态链接库，改变指定进程的运行速率。"}},
	{ GenshinImpact, {"Start Genshin Impact. (Yuanshen, Qi Dong!!) (WIP)", "启动原神。（原神，启动！）（还没做好）"}},
	{ Tasklist, {"Output Tasklist in Console." , "在控制台输出进程列表。"}},
	{ Run, {"Run specified process.", "运行指定进程。"}},
	{ DebugESP, {"Receive and output debug strings of processes.", "接收并输出进程的调试字符串。"}},
	{ ProcessESP, {"Detect the specified processes and process changes." , "探测指定进程以及进程变化。"}},
	{ CompileESP, {"Monitor compiler processes and notify compile start/finish.", "监控编译器进程并通知编译开始/结束。"}},
	{ ProcessKill, {"Kill the specified process." , "杀死指定进程。"}},
	{ ProcessKeep, {"Restart the specified process if it's killed." , "如果指定进程被结束，则重新启动它。"}},
	{ ProcessFreeze, {"Freeze the specified process." , "冻结指定进程。"}},

	{ FileManager, {"Manage files and folders." , "管理文件和文件夹。"}},
	{ ProcessManager, {"Manage processes with a visual manager app." , "使用可视化管理器管理进程。"}},
	{ Everything, {"Everything software utilities.", "软件“Everything”的一些功能。"}},
	{ PeParser, {"Parse PE structures (headers, sections, imports, exports).", "解析PE结构（头、节区、导入、导出）。"}},
	{ HexViewer, {"View files in hexadecimal format." , "以十六进制格式查看文件。"}},
	{ DiskMissing, {"Create the illusion of disk loss.", "制造磁盘丢失的假象。"}},
	{ FileDelete, {"Delete the specified file." , "删除指定文件。"}},
	{ FileCreate, {"Create the specified file." , "创建指定文件。"}},
	{ FileMonitor, {"Monitor file changes in a folder.", "监视一个目录下的文件变化。"}},
	{ FolderClear, {"Clear the specified folder." , "清空指定目录。"}},
	{ TempClear, {"Clear the Windows temp folder.", "清空系统临时目录。"}},
	{ RubbishClean, {"Clear the system rubbish.", "清理系统垃圾。"}},
	{ RecyclerClear, {"Clear the Windows Dustbin.", "清空系统回收站。"}},
	{ RootProgram, {"Policies on the disk root Program Glitch." , "针对驱动器根目录下Program文件夹漏洞的政策。"}},
	{ PrivacySpy, {"Collect user's privacy information according to local files, making you nervous", "根据本地文件汇总用户的隐私信息，让你变得紧张"}},
	{ PrivacyDatabase, {"A useful database to store privacy. (PRO)", "一个有用的隐私数据库。（专业版）"}},
	{ SelfBackup, {"Backup all assets to the backup folder.", "把所有资产备份到backup文件夹。"}},
	{ SelfRestore, {"Restore all assets from the backup folder." , "从backup文件夹恢复资产。"}},
	{ AutoRestore, {"Auto monitor & restore own missing assets." , "自动监视并恢复缺失的资产。"}},

	{ RegMonitor, {"Monitor registry changes. (WIP)", "监视注册表变化。（维护中）"}},
	{ SecureLogin, {"Require users to press Ctrl+Alt+Delete before signing in.", "要求用户在登录前先按下 Ctrl+Alt+Delete。"}},
	{ ListHijacks, {"List all Image Hijacks in the registry.", "枚举注册表内所有的映像劫持。"}},
	{ KillHijacks, {"Clear all Image Hijacks in the registry.", "清空注册表内所有的映像劫持。"}},
	{ NoCmd, {"Disable the Command Prompt.", "禁用命令提示符。" }},
	{ NoPowerShell, {"Disable the PowerShell.", "禁用 Powershell。" }},
	{ NoTaskmgr, {"Disable the Task Manager.", "禁用任务管理器。" }},
	{ NoRegedit, {"Disable the Registry Editor.", "禁用注册表编辑器。" }},
	{ NoDesktopIcons, {"Disable the desktop icons. Need to restart explorer.exe.", "禁用桌面图标。需要重启资源管理器。" }},
	{ NoDesktopMenu, {"Disable the desktop menu. Need to restart explorer.exe.", "禁用桌面菜单。需要重启资源管理器。" }},
	{ NoTaskbarMenu, {"Disable the taskbar menu. Need to restart explorer.exe.", "禁用任务栏菜单。需要重启资源管理器。" }},
	{ NoStartMenuChange, {"Disable the change of Start Menu. Need to restart explorer.exe.", "禁用开始菜单的变化。需要重启资源管理器。" }},
	{ NoRun, {"Disable the Run dialog.", "禁用Win+R运行对话框。" }},
	{ NoPowerOptions, {"Disable the power options on the Start Menu.", "禁用开始菜单上的电源选项。" }},
	{ NoLogOff, {"Disable the Logoff button.", "禁用注销按钮。" }},
	{ NoDwm, {"Disable DWM process. Need to reboot.", "禁用桌面窗口管理器进程。需要重启计算机。"}},
	{ NoConsoleAltF4 , {"Disable Alt+F4 Shortcut in Console.", "禁用控制台中的 Alt+F4 快捷键。" }},
	{ NoSetFolders, {"Disable the Set Folders function in explorer. Need to restart explorer.exe.", "在资源管理器禁用设置文件夹。需要重启资源管理器。" }},
	{ NoFolderOptions, {"Disable the Folder Options in explorer. Need to restart explorer.exe.", "在资源管理器禁用文件夹选项。需要重启资源管理器。" }},
	{ HideWindowsUpdate, {"Hide Windows Update in explorer. Need to restart explorer.exe.", "在资源管理器隐藏系统更新入口。需要重启资源管理器。" }},
	{ UpdateDisabler, {"Delay Windows Update time to the maximum while enabled, and restore to current time when disabled. (Admin Required)", "开启时将 Windows 更新时间推迟到最大值，关闭时恢复为当前时间。（需要管理员）" }},
	{ NoWinKeys, {"Disable all the Win-Keys.Need to restart explorer.exe.", "禁用一些Win开头的快捷键。需要重启资源管理器。" }},
	{ NoLockUser, {"Disable the Lock User Workstation operation (including Win+L hotkey).", "禁用锁定用户的操作。包括Win+L快捷键。" }},
	{ RestrictRun, {"Permit and run only certain apps in Windows to run.", "限制系统中所有的程序运行。" }},
	{ NoMSDos, {"Disable the MS-DOS.", "禁用MS-DOS。" }},
	{ NoSmartScreen, {"Disable Microsoft SmartScreen.", "禁用微软 SmartScreen。"}},
	{ NoRemovableDev, {"Disable the removable devices. (UNSTABLE)", "禁用所有可移动设备（不稳定）。" }},
	{ NoDefender, {"Disable the Windows Defender Realtime Protection. (UNSTABLE)", "禁用 Windows Defender 的实时保护。（不稳定）" }},
	{ NoHibernate, {"Disable the hibernation of the system.", "禁用系统的休眠功能。" }},
	{ NoFastStartup, {"Disable the fast startup of the system.", "禁用系统的快速启动功能。"}},
	{ NoRemoteDesktop, {"Disable the Remote Desktop feature.", "禁用远程桌面功能。"}},
	{ NoUAC, {"Disable the User Account Control. It can take effect without rebooting Windows, actually.", "禁用用户账户控制（UAC）。" }},

	{ Arraylist, {"Display an arraylist of enabled modules.", "显示已启用模块列表。"}},
	{ Ambience, {"Simulate the ambience such as weather and lighting.", "模拟环境，如天气和光照。"}},
	{ AutoDanmaku, {"Automatically send danmaku according to the xml file.", "根据xml文件自动发送弹幕。"}},
	{ AutoTitle, {"Automatically enable the Title Module according to rules.", "根据规则自动启用标题模块。"}},
	{ AutoTotem, {"Play totem pop animation automatically.", "自动播放爆图腾动画。"}},
	{ HighContrast, {"Enable the High Contrast mode of Windows." , "打开系统的高对比度模式。"}},
	{ BetterLyrics, {"Recognize the lyrics and display them in a better way.", "识别歌词并以更好的方式显示。"}},
	{ MusicOverlay, {"Display an overlay showing music information. (PRO)", "显示一个覆盖层，展示音乐信息。（专业版）"}},
	{ LyricsPhysics, {"Apply physics effects to the lyrics on the audio visualizer.", "在音频可视化器上应用物理效果到歌词。"}},
	{ BlackCapture, {"In any recording software, this client is in black." , "在任何截图或录屏软件中，客户端是黑屏的。"}},
	{ ScreenSaver, {"Start the system screensaver program.", "启动系统的一个屏幕保护程序。"}},
	{ CloseMonitor, {"Close the monitor." , "发送关闭显示器的信号。"}},
	{ Crosshair, {"Draw crosshair. There are some other functions in Advanced Mode." , "绘制一个准星。在高级模式有一些其他功能。"}},
	{ MouseESP, {"Highlight the position of the mouse cursor.", "高亮鼠标指针的位置。"}},
	{ MouseTrails, {"Enable mouse trails." , "显示鼠标轨迹。"}},
	{ Keystrokes, {"Display keystrokes for gaming." , "显示游戏按键。"}},
	{ Keystrokes2, {"Display keystrokes below dynamically." , "在下方动态显示你的按键。"}},
	{ LetterGraph, {"Display a graph counting letters.", "呈现字母数量的图表。"}},
	{ NoAnimation, {"Disable some of the animations in Windows." , "关闭系统的一些动画。"}},
	{ NoScreenSaver, {"Disable the screensaver." , "禁用屏幕保护程序。"}},
	{ PerformanceHUD, {"Show client/system performance usage.", "显示客户端/系统性能占用。"}},
	{ DownloadHUD, {"Display client's file downloading progress.", "显示客户端文件下载进度。"}},
	{ SessionHUD, {"Display information of current user.", "显示当前用户的信息。"}},
	{ PPLESP, {"Display all the ppl in the left (Sirius.sys Required).", "在左侧显示所有受保护进程。（需要Sirius驱动）"}},
	{ SecurityESP, {"Display a malware and antivirus list in the right." , "在右侧显示病毒和杀软列表。"}},
	{ ClipboardESP, {"Display the clipboard contents in the left." , "在左侧实时显示剪贴板内容。"}},
	{ MCDisplay, {"Display Minecraft HUD elements.", "显示 Minecraft 的 HUD 元素。"}},
	{ MotionBlur, {"Apply motion blur effects on the screen.", "在屏幕上应用动态模糊。"}},
	{ Background, {"Client background settings.", "客户端背景设置。"}},
	{ WarpUI, {"Synchronizes pseudo-3D visual warping with precise GUI interaction mapping.", "将伪 3D 视觉形变与 GUI 交互坐标精确同步的界面形变"}},
	{ GUIBlur, {"Apply blur effect to the GUI.", "应用模糊效果到GUI。"}},
	{ HUDBlur, {"Apply blur effect to the HUD.", "应用模糊效果到HUD。"} },
	{ CustomHUD, {"Customize the HUD elements.", "自定义 HUD 元素。"}},
	{ HudEditor, {"Help you edit the atrributes of HUD elements.", "帮助你编辑 HUD 元素的属性。"}},
	{ ModuleEditor, {"Visually edit module visibility in the GUI. Click modules to toggle their hidden state.", "在 GUI 中可视化编辑模块的显示/隐藏状态。点击模块即可切换其隐藏状态。"}},
	{ TimeDisplay, {"Show current time, and give you a message every half hour." , "显示时间，然后每半个小时报一次时。"}},
	{ Island, {"Display a cool dynamic island.", "显示一个酷炫的灵动岛。"}},
	{ Karaoke, {"Render karaoke lyrics with progress highlighting.", "以卡拉OK进度高亮方式显示歌词。"}},
	{ Title, {"Display a title in the center of the screen.", "在屏幕中央显示一个标题。"}},
	{ FancyTexts, {"Display fancy texts with animations and effects.", "显示一些带有动画和特效的花哨文字。"}},
	{ Actionbar, {"Display an actionbar message.", "显示一条动作栏消息。"}},
	{ Totem, {"Play Totem of Undying animation.", "播放不死图腾的动画。"}},
	{ Tint, {"Apply global color to the client texture.", "应用全局颜色到客户端纹理。"}},
	{ Stuck, {"Freeze your screen.", "冻结你的屏幕画面。"}},
	{ Watermark, {"Draw Watermark in the center of the screen." , "屏幕中央绘制水印。"}},
	{ BlackoutSense, {"Detect laptop blackout and trigger configured action after countdown. (PRO)", "检测笔记本断电并在倒计时后执行设定动作。（专业版）"}},
	{ PowerSaving, {"Save power by reducing render effects and FPS.", "通过削弱渲染效果和限制帧率来节能。"}},
	{ WeakView, {"Enable the energy-saving mode of system.", "打开系统节电模式。"}},
	{ Bright, {"Adjust the brightness of the monitor.", "调节屏幕亮度。"}},
	{ Gamma, {"Adjust the gamma of the monitor. (Microsoft: Not Recommended)" , "覆写显示器伽马亮度值（微软不推荐）。"}},
	{ Spotlight, {"Enable a spotlight when double press Ctrl." , "双击 Ctrl 后在光标的地方显示一个光斑。"}},
	{ Shaders, {"Apply specified shaders to the client." , "应用一些着色器。"}},
	{ Night, {"Enable the Night Mode." , "启动夜间模式。"}},

	{ IRC, {"An improved brand-new online chat system.", "完善的新版在线聊天系统。"}},
	{ IRCLegacy, {"Legacy IRC chat system (hidden).", "旧版聊天室，纯由HTTP轮询实现，性能较差。"}},
	{ AntiWebpage, {"Automatically close bad webpages.", "自动关闭不好的网页。"}},
	{ LiveChatter, {"Manage live chatter interactions (receive/send/AI responses).", "管理直播间弹幕交互（接收/发送/AI回复）。"}},
	{ TcpMonitor, {"Monitor changes of TCP connections of specified processes.", "监视指定进程的TCP连接的变化。"}},
	{ TcpKiller, {"Kill certain TCP connections of specified processes.", "断开指定进程的某些TCP连接。"}},
	{ OnlineTime, {"Get the online time.", "获取在线时间。"}},
	{ IPTracker, {"Display current external IP address and location as a HUD overlay.", "将当前外网IP地址与地理位置显示为HUD覆盖层。"}},
	{ IPAddress, {"Look up IP Addresses and relevant info of current computer.", "查看本机IP地址及相关信息。"}},
	{ IPHorror, {"Assemble a scary paragraph based on the provided IP address", "根据提供的IP地址组装一个吓人的段落"}},
	{ PhoneArea, {"Query the phone number area code and carrier." , "查询电话号码的地区码和运营商。"}},
	//{ WallCheck, {"Check if a website is blocked. (Not work)", "检测一个网站是否被墙。（不能正常工作）"}},
	{ WeatherInfo, {"Some weather utilities.", "一些天气方面的功能。"} },
	{ QuakeWarning, {"Warns you when an earthquake is coming.", "地震来临时提供预警。"}},
	{ Encryptor, {"Helps you encrypt specified text.", "帮助你加密指定的文本。"}},
	{ NickGenerator, {"Generate random nicknames in multiple styles.", "生成多风格随机昵称。"}},
	{ Memeizer, {"Generate wierd machine translation based on the provided text.", "基于提供的文本生成逆天的机器翻译。"}},
	//{ BiliCookies, {"Get or Clear the Cookies of Bilibili.", "获取或清除B站Cookies。"}},
	{ BiliChatter, {"Simulate Bilibili chatters in some videos.", "模拟B站一些视频的弹幕。"}},
	{ BiliConsole, {"A userful interactive console to operate bilibili.", "一个实用的交互式B站控制台。"}},
	{ BiliFans, {"Monitor Bilibili fans and send notifications.", "监控B站粉丝并发送通知。"}},
	{ BiliFeed, {"Obtain several recommended videos from Bilibili", "从B站获取一些推荐视频。"}},
	{ BiliHot, {"Display the hot searches of Bilibili.", "显示B站热搜。"}},
	{ BiliNotifier, {"Send Bilibili notifications to you.", "向你发送B站的通知。"}},
	{ BiliProfile, {"Make a profile of the specified Bilibili user.", "为指定的B站用户生成一个档案。"}},
	{ BiliSettings, {"Settings about the account of Bilibili. Enable to login.", "有关B站账号的设置。启用以登录。"}},
	{ WebSettings, {"Settings about client network.", "客户端联网设置。"}},
	{ AISettings, {"Settings about the AI.", "关于AI的设置。"}},
	{ ApiHzSettings, {"Settings about ApiHz translation interface.", "关于 ApiHz 翻译接口的设置。"}},
	{ Agent, {"Use a simple ai agent to complete your task.", "使用一个简单的人工智能代理完成你的任务。"}},
	{ Translator, {"Simple translation service.", "一个简单的翻译服务。"}},
	{ BiliVideo, {"Query and output the information of the specified Bilibili video.", "查询并输出指定的B站视频的信息。"}},
	{ BiliVideoCover, {"Parse and extract the cover of the specified Bilibili video.", "解析并提取指定的B站视频的封面。"}},
	{ BiliVideoHelper, {"Monitor the foreground Bilibili video window and display relevant information.", "监视前台哔哩哔哩视频窗口，显示相关信息。"}},
	{ LiveStream, {"Some live stream utilities.", "一些直播间的功能。"}},
	{ Streamer, {"Prevents any accidents when streaming.", "防止直播过程中发生意外。"}},
	{ QQBot, {"A simple QQ bot.", "一个简单的QQ机器人。"}},
	{ QQInspect, {"Inspect local QQ basic info if you keeps that glitch.", "如果漏洞存在，则窥探你的基本QQ信息。"}},
	{ SystemProxy, {"Set the system Internet proxy.", "设置系统因特网代理。"}},
	{ Flight, {"Toggle the flight mode.", "打开/关闭飞行模式。"}},

	{ AntiAFK, {"Move the mouse periodically to avoid being detected as AFK.", "周期性移动鼠标，防止被检测成挂机。" }},
	{ AntiRickroll, {"Prevent any Never Gonna Give You Up Windows from appearing.", "防止任何 Never Gonna Give You Up 窗口出现。" }},
	{ AutoClicker, {"Automatically Helps you to click very fast.", "自动帮助你飞快地点击鼠标。"}},
	{ AutoSpeak, {"Automatically speak something.", "自动说出一些话。"}},
	{ BridgeAssist, {"Helps you to bridge in Minecraft.", "在MC辅助你搭路。" }},
	{ ChatAsk, {"Fill your prompt with answer from AI when hotkey is pressed.", "快捷键按下时用人工智能回答你输入的内容。" }},
	{ ChatTranslate, {"Translate your prompt with AI when hotkey is pressed.", "快捷键按下时人工智能翻译你输入的内容。" }},
	{ ChatBilingual, {"Add a translation from AI to your prompt when hotkey is pressed.", "快捷键按下时人工智能把你输入的内容变成双语。" }},
	{ ChatRestruct, {"Restruct your words with AI when hotkey is pressed.", "快捷键按下时人工智能用特定方式重构你输入的内容。" }},
	{ AutoCopy, {"Automatically copy the specific text.", "自动复制指定的文本。"}},
	{ ClipboardTweaks, {"Some useful utilities about clipboard.", "一些剪贴板的实用功能。"}},
	{ MinecraftUtils, {"Some useful utilities on Minecraft.", "一些MC上的实用功能。"}},
	{ ChatQueue,{"Manage the Minecraft chat send tasks.", "管理MC的聊天发送任务。"}},
	{ AutoText, {"Automatically send specified texts in some situations.", "特定情况下自动发送指定文本。"}},
	{ AutoL, {"Automatically send critical texts when enemies died.", "敌人死亡时自动发送嘲讽信息。"}},
	{ MemeTrigger, {"Trigger specified meme when you press RCtrl/RShift + AlphaKey.", "在按下右Ctrl/右Shift+字母键时触发一些特定的梗。" }},
	{ MouseTeleport, {"Teleport the mouse in certain situations.", "在某些场合下传送鼠标。"}},
	{ MouseWatcher, {"Watch the movement and interaction of the mouse.", "监视鼠标移动和交互。"}},
	{ MouseSwap, {"Swap mouse buttons.", "交换鼠标左右键。" }},
	{ ColorPicker, {"Show and copy the color at the cursor point.", "显示和复制鼠标位置的颜色。"}},
	{ NoDoubleClick, {"Disable mouse double click.", "禁用鼠标双击。" }},
	{ NoClipboard, {"Clear the clipboard if it's not empty.", "如果剪贴板有东西，立即清空。" }},
	{ MouseDisabler, {"Disable the mouse with mouse hooks.", "用鼠标钩子禁用鼠标。" }},
	{ BHop, {"Helps you jump continuously. (PRO)", "帮助你连续跳。（专业版）"}},
	{ SnapTap, {"Automatically releases a previously held key when a new key (A/D) & (W/S) is pressed.", "按下新键（A/D）和（W/S）时，自动释放之前按住的键。"}},
	{ ToggleKey, {"Helps you hold some keys until you repress it.", "帮助你持续按住一些键，直到你再次按下它。"}},
	{ Typewriter, {"Automatically type some paragraphs.", "自动帮你输入段落。"}},
	{ TypingPractice, {"A typing mini game that records your best completion time.", "一个会记录最佳成绩的打字小游戏。"}},
	{ CapsGuard, {"Keeps the state of CapsLock.", "保持大写锁定键的状态。" } },
	//{ Spammer, {"Automatically spam some messages.", "自动刷一些消息。"}},
	{ KeyDisabler, {"Disable some keys with keyboard hooks.", "用鼠标钩子禁用一些按键。" }},
	{ KeyLogger, {"Log all the keys pressed to the output folder.", "记录所有的按键到output文件夹。" }},
	{ KeySound, {"Custom different key sounds for any keys or hotkeys.", "为任意的键或者快捷键自定义不同的按键声音。" }},
	{ KeyReaction, {"Perform certain actions when some keys are pressed.", "当按下某些键时执行某些操作。"}},
	{ TypingEffects, {"Display some effects while typing.", "打字时展示一些特效。"}},
	{ CaretBrowser, {"Allows you to navigate the caret with the keyboard in more situations. (WIP)", "允许你在更多的场景下使用键盘导航光标。(WIP)"}},
	{ MacroRecorder, {"Record macros of keyboard and mouse actions.", "录制键盘和鼠标操作的宏。"}},
	{ MacroPlayer, {"Play macros of keyboard and mouse actions.", "播放键盘和鼠标操作的宏。"}},
	{ NoBeep, {"Disable the beep.", "禁用蜂鸣器。" }},
	{ RestartExplorer, {"Restart the explorer.exe.", "重启资源管理器。" }},
	{ QuickIME, {"Use one key to toggle global Input Method.", "用一个按键去切换全局输入法。"}},
	{ DisableIME, {"Disable global Input Method once.", "单次禁用全局输入法。" } },
	{ NoIME, {"Keep disabling global Input Method.", "保持禁用全局输入法。" }},
	{ Panic, {"Disable all the modules immediately.", "尝试立即关闭所有模块。" }},
	{ Musics, {"Play music.", "播放音乐。"}},
	{ Speaker, {"Call the Windows Speaker to make a speech.", "调用 Windows 的讲述人念一段文本。"}},
	{ Volume, {"Help you to adjust the volume.", "帮你调节音量。" }},
	{ Mixer, {"Show the volumes of all processes that produce sound.", "显示所有所有发声的进程的音量。"}},
	{ AudioIsolation, {"Only one process can produce sound.", "只有一个进程可以发出声音。"}},
	{ CloudMusic, {"A simple hook of netease cloud music.", "一个简单的网易云音乐的挂钩。"}},
	{ Mute, {"Mute the current audio device.", "让当前音频设备静音。" }},
	{ Active, {"Keep the client focused all the time.", "始终让客户端窗口获得焦点。" }},
	{ AudioVisualizer, {"Show the audio waveform or other forms of visualization.", "显示音频波形或其他形式的可视化。"}},
	{ GUIStyler, {"Set GUI style according to specific presets.", "根据预设设定GUI风格。" }},
	{ ForceTopmost, {"Force this client to be topmost with a running thread.", "用线程强制本客户端为置顶窗口。" }},
	{ Triggers, {"Periodically check conditions and trigger tasks.", "定期检查条件并触发任务。"}},
	{ NotificationModule, {"Show client notifications.", "显示客户端的通知。"}},
	{ Reminder, {"Someone would like to care about you.", "想要关心你的某一个人。"}},
	{ IQBooster, {"Boost your IQ secretly.", "暗中提高你的智商。"}},
	{ TimeManager, {"Change the system time and its flowing speed.", "调整系统时间及其流速。"}},
	{ TaskbarIcon, {"Whether to show taskbar icon.", "是否显示任务栏图标。"}},
	{ ScreenCapture, {"A background thread that keeps capturing the screen.", "一个持续捕捉屏幕的后台线程。"}},
	{ AsciiArtConvert, {"Convert an image into colorful ASCII art and output it to console or file.", "将图像转换为彩色字符画并输出到控制台或文件。"}},
	{ QuickCommand, {"Press hotkey to open a input box, and quickly execute some commands.", "按快捷键打开输入框，输入后快速执行一些命令。"}},
	{ Shell, {"Open the client shell.", "打开客户端命令行。" }},
	{ OpenUrl, {"Open a URL in the default browser.", "在默认浏览器打开链接。" }},
	{ Screenshot, {"You can take a screenshot using PrintScreen key. ", "你可以用PrtScr键打开截图工具。"}},
	{ TesseractOCR, {"Tesseract OCR Settings.", "Tesseract 文字识别设置。"}},
	{ Console, {"Enable the Console.", "启动控制台。" }},
	{ Developer, {"For developers.", "开发者模式。"}},
	{ Hidden, {"Hide main window and minimize into the tray.", "隐藏主窗口，最小化至托盘。"}},
	{ Restart, {"Restart the client.", "重启客户端。" }},
	{ Exit, {"Quit the client.", "退出客户端。" }},

	{ RTCore64, {"For PPL Settings.", "为受保护进程设定。" }},
	//{ DisableHR, {"Kill Huorong Antimalware.", "杀死火绒。" }},
	{ Kernel1, {"Kernel Tools 1", "内核工具（一）"}},
	{ Sirius, {"Sirius Kernel Tools - Advanced process management driver.", "天狼星内核工具 - 高级进程管理驱动。"}},

	{ Anti360Ad, {"Punish 360 Ads. (UNSTABLE)" , "惩罚一些360的广告。（不稳定）"}},
	{ Anti360VT, {"Disable the virtualization technology of 360 antivirus.", "禁用360的虚拟化技术。"}},
	{ ScaredUAC, {"Make UAC Prompt move." , "让UAC弹窗移动。"}},
	{ KillEveryone, {"Attempt to kill every process (except 0 and myself)" , "尝试杀死除0和自身外的其他一切进程。"}},
	{ KillAV, {"Kill Every Antivirus Process registered in my process profile with a driver." , "使用驱动程序杀死注册在档案中的杀软进程。"}},
	//{ CloseAV, {"Take measures to close some Antivirus software. (WIP)", "采取一些措施关闭一些杀软。（没做好）"}},
	{ KillMalware, {"Kill Every Malware Process registered in my process profile." , "杀死每一个已注册的恶意程序进程。"}},
	{ KillHuorong, {"Kill all Huorong processes using a driver.", "用驱动杀死火绒所有进程。"}},
	{ Kill360, {"Kill all 360 processes using a driver.", "用驱动杀死360所有进程。"}},
	{ Kill360Test, {"Ring3 Kill 360. (Just Test)", "三环杀数字。（只是测试）"} },
	{ Kill360AdProc, {"Kill 360 Ad Processes.", "杀死360的广告进程。"}},
	{ FreezeExplorer, {"Attempt to freeze explorer.exe (Failure may be not real)", "尝试冻结资源管理器。（失败可能只是表象）"}},
	{ FreezeEveryone, {"Attempt to freeze every process (except 0 and myself)", "尝试冻结0和自身以外的一切进程。"}},
	{ UnfreezeEveryone, {"Attempt to unfreeze every process (except 0 and myself)" , "尝试解冻0和自身以外的一切进程。"}},
	{ PPLButcher, {"Attempt to kill every PPL (Sirius Required, Not Recommended).", "尝试解除每一个受保护进程的保护。（需要 Sirius 驱动，不推荐）"}},
	{ ACGButcher, {"Attempt to disable the DynamicCodePolicy of every process.", "尝试关闭一切进程的动态代码政策。"}},
	{ TrustedInstaller, {"Granted with TrustedInstaller privileges. (UNSTABLE)" , "重启客户端获得受信任安装者权限（不稳定）。"}},
	{ RemoteKillHR, {"Kill Huorong Antimalware using remote thread. (WIP)", "用远程线程让其他进程杀火绒（没做好）。"}},
	{ Masquerade, {"Masquerade as explorer.exe by modifying PEB.", "修改PEB伪装成资源管理器。"}},
	{ NoNotification, {"Attempt to disable Windows Notification. (WIP)", "尝试关闭系统通知（没做好）"}},
	{ RuinAura, {"Ruin every target window. (WIP)" , "搞坏每一个目标窗口（没做好）"}},
	{ SelfDestruct, {"Delete myself (exe) immediately.", "立即删除客户端自身EXE。"}},
	{ SelfUninstall, {"Uninstall this client (entire folder) immediately.", "立即卸载整个客户端。"}},
	{ HideProcess, {"Hide processes from Task Manager using Sirius driver.", "使用 Sirius 驱动隐藏进程。"}},
	{ Vape, {"Draw Vape Logo. It's kind of cool", "绘制电子烟的标志。有点帅。"}},
	{ Portal, {"Control teleportation of different desktops.", "控制不同桌面间的传送。"}},
};

string GetModuleDescription(ModuleID mid);